### PR TITLE
enable python support for ros2

### PR DESCRIPTION
**Pull request by ahuizxc**
Modified some files to enable this package support python.

### CODE REVIEW

**Comment by ahuizxc** [comment]
@mjcarroll :) please review this PR if you are free thanks.

**Comment by mjcarroll** [comment]
I think it may be better to do it this way: https://github.com/ros-perception/vision_opencv/pull/257  That way we don't have to maintain the `setup.py` file as well.

**Comment by ahuizxc** [comment]
> I think it may be better to do it this way: #257 That way we don't have to maintain the `setup.py` file as well.

Nice job！

**Comment by mjcarroll** [comment]
Superseded by #257

**Pull request closed without merging**
