### PR TITLE
Deprecate .h files in favor of .hpp headers

### PR DESCRIPTION
**Pull request by ijnek**
Resolves: #262

### CODE REVIEW

**Comment by ijnek** [comment]
@wep21 would you be able to review this PR?

**Comment by ijnek** [comment]
@wep21 would you be able to review this PR?

**Comment by wep21** [comment]
I checked all the .h include files are replaced with .hpp include files.

**Comment by chhtz** [comment]
Is there a recommended way to include cv_bridge while staying compatible with older ros distros? (We have a project which ideally should build with Ubuntu20, 22, and 24).
This project made a workaround by checking the distro-name from cmake (this does not look very future-proof, though):
https://github.com/pf-robotics/kachaka-api/pull/149/files

**Comment by wep21** [comment]
@chhtz I guess using `__has_include` is the most easiest way to support multi distro.
https://github.com/pal-robotics/aruco_ros/blob/2eba69e025bb1a7a858792d097270a9f959ab095/aruco_ros/src/simple_double.cpp#L43-L47

**Comment by chhtz** [comment]
@wep21 Indeed I was just starting to write a comment with that solution.

```
#if __has_include("cv_bridge/cv_bridge.hpp")
#  include "cv_bridge/cv_bridge.hpp"
#else
#  include "cv_bridge/cv_bridge.h"
#endif
```

(`__has_include` is defined since gcc 4.9.2 and at least clang 3.0, so it is pretty safe to use at least under Linux. I don't use/did not check MSVC)

**Pull request merged**
