### PR TITLE
Cleanup opencv_apps CMakeLists.txt by using link_libraries macro

### PR DESCRIPTION
**Pull request by garaemon**
Remove many `target_link_libraries` and use one `link_libraries`

### CODE REVIEW

**Comment by vrabaud** [comment]
link_libraries is deprecated: https://cmake.org/cmake/help/v3.0/command/link_libraries.html?highlight=link_libraries

**Comment by vrabaud** [comment]
any good reason why you wanted to use it ? Or just clarity ?

**Comment by garaemon** [comment]
> just clarity ?

Yes

**Comment by garaemon** [comment]
> link_libraries is deprecated: https://cmake.org/cmake/help/v3.0/command/link_libraries.html?highlight=link_libraries

oh...

**Pull request closed without merging**
