### PR TITLE
To use fisheye undistotion

### PR DESCRIPTION
**Pull request by zgxsin**
Update the code to work with distortion model [EQUIDISTANT](http://docs.ros.org/melodic/api/sensor_msgs/html/distortion__models_8h.html)

### CODE REVIEW

**Comment by zgxsin** [comment]
@vrabaud Could you review this MR? `EQUIDISTANT` distortion model  is defined in `image_geometry` package, but not implemented. I think this is a bug. I have already used this MR for Equidistant model. It works well.

**Comment by YoshuaNava** [comment]
Dear @vrabaud and @mjcarroll,
My colleague @zgxsin has implemented the equidistant distortion model. We have internally tested this and found that it leads to lower reprojection error (measured with Kindr) when matching corner features collected from rectified images.

We would be really interested in doing anything needed to contribute this to your repo and have it on master soon. We don't want to diverge from the main development branch and miss the chance to contribute our changes to the robotics community.

Please let us know your thoughts.

Best regards,
Yoshua Nava

**Comment by mintar** [comment]
This PR can be closed, since #358 was finally merged.

**Comment by YoshuaNava** [comment]
@mintar Thank you for taking forward #358 and pushing for it to be merged, it is a really nice contribution. :pray:

**Comment by zgxsin** [comment]
> This PR can be closed, since #358 was finally merged.

Thanks. Close it now.

**Pull request closed without merging**
