### PR TITLE
Add OpenCV4 support

### PR DESCRIPTION
**Pull request by solosito**
PR of changes from #288 to ros2 branch

### CODE REVIEW

**Comment by hgaiser** [comment]
As mentioned in https://github.com/ros-perception/vision_opencv/pull/259 , we should drop support for OpenCV 2 entirely as it is not a target for melodic and up (and therefore also ROS2) and only makes it more complex and less future proof. In my opinion we should use https://github.com/ros-perception/vision_opencv/pull/259 but it has been ignored for a while now.

**Comment by bbferka** [comment]
Will opening a fourth PR on this topic make it more likely that this fix gets eventually merged? :smile:

**Comment by OAkyildiz** [comment]
I think @solosito intended these changes for melodic, but it was forked from ros2 and tested with Melodic on Trusty Thar. I see that @mjcarroll labeled this as `ros2`.

 Creating a new pull request with CI test for Melodic/Bionic environment and referring this issue and #288

**Comment by mjcarroll** [comment]
Apologies,  I'm going to go ahead and run this through CI targeting `foxy` and `focal`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9814/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5440/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7983/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9678/)

**Comment by mjcarroll** [comment]
I'm also in favor of dropping OpenCV2 support as it isn't on any of our target platforms for the `foxy` release.

**Comment by ijnek** [comment]
I'm going to close this off as I believe it's been resolved in https://github.com/ros-perception/vision_opencv/pull/324.

**Pull request closed without merging**
