### PR TITLE
feat: add type adapter for cv::Mat

### PR DESCRIPTION
**Pull request by wep21**
I add type adapter for cv::Mat. I just import the feature from [image_tools](https://github.com/ros2/demos/tree/master/image_tools).

### CODE REVIEW

**Comment by wep21** [comment]
@audrow Could you review this? I just import the feature you created from image_tools.

**Review by audrow — COMMENTED** [review]
Thanks for the PR, @wep21. The code looks fine, as it was just copied over.

One thing is that type adaption only works for Humble and Rolling, so the PR jobs for Foxy and Galactic will always fail. Maybe this requires a new way of branching the repository to split Humble and Rolling. For that, I'll ping the maintainers: @gaoethan.

Also, @wjwwood, is there any way we can avoid this duplication, or is this desirable to do at all?

Lastly, for Rolling and Humble, it seems that the PR jobs are failing (ie, `Rpr_*` and `Hpr_*`) in the same ways. I didn't take much of a look, but don't see those failures in past PR jobs for the ros2 branch. Maybe it's something introduced in this PR?

**Comment by wep21** [comment]
@audrow @gaoethan I fixed python test in https://github.com/ros-perception/vision_opencv/pull/444. I appreciate it if you could review it, too.

**Comment by audrow** [comment]
@ros-pull-request-builder retest this please

**Comment by wep21** [comment]
@audrow Is it better to create a new branch for `foxy` or `galactic`?

**Comment by ijnek** [comment]
> @audrow Is it better to create a new branch for `foxy` or `galactic`?

Related: [#393 foxy and galactic branches?](https://github.com/ros-perception/vision_opencv/issues/393)

**Comment by wep21** [comment]
@audrow friendly ping

**Review by audrow — COMMENTED** [review]
> @audrow Is it better to create a new branch for `foxy` or `galactic`?

Yeah, now that I think of it, we're going to have to create those branches and setup CI before this can be merged in. Type adaptation was introduced in Humble, so nothing earlier will work.

@vrabaud, what do you think?

**Comment by ijnek** [comment]
I've gone ahead and split off foxy, galactic and humble branches, and once https://github.com/ros/rosdistro/pull/34314, CI should only run on rolling.

@audrow Since you've said you're fine with the changes in a previous comment, I'm going to proceed with merging the PR in (but not backport to humble since its a new feature). Over in [demos/image_tools](https://github.com/ros2/demos/tree/master/image_tools), a PR can be reaised to use the class from cv_bridge instead. If you're fine with that, could you simply leave a reaction? Otherwise, we can discuss.

**Comment by audrow** [comment]
> @audrow Since you've said you're fine with the changes in a previous comment, I'm going to proceed with merging the PR in (but not backport to humble since its a new feature). Over in [demos/image_tools](https://github.com/ros2/demos/tree/master/image_tools), a PR can be reaised to use the class from cv_bridge instead. If you're fine with that, could you simply leave a reaction? Otherwise, we can discuss.

That all sounds good to me - thanks, @ijnek!

> I've gone ahead and split off foxy, galactic and humble branches, and once https://github.com/ros/rosdistro/pull/34314, CI should only run on rolling.

By the way, if you want to be more consistent with most of the ROS 2 core repositories, you can change the `ros2` branch to `rolling`.

**Comment by ijnek** [comment]
> By the way, if you want to be more consistent with most of the ROS 2 core repositories, you can change the ros2 branch to rolling.

Yep, that's the plan. I'm not sure what the unintended consequences are of renaming the branch are, so I'm going to be careful about it. You'd probably know more about this since you did the changes for the core repositories?

**Comment by ijnek** [comment]
> By the way, if you want to be more consistent with most of the ROS 2 core repositories, you can change the ros2 branch to rolling.

Yep, that's the plan. I'm not sure what the unintended consequences are of renaming the branch are, so I'm going to be careful about it. You'd probably know more about this since you did the changes for the core repositories.

**Comment by ijnek** [comment]
@ros-pull-request-builder retest this please

**Comment by ijnek** [comment]
Branches have been updated, so only the output of Rolling CI is important here. Since it's passing, I'll merge.

**Comment by ijnek** [comment]
Thanks for the contribution @wep21 and reviewing @audrow !

**Comment by ijnek** [comment]
> Over in [demos/image_tools](https://github.com/ros2/demos/tree/master/image_tools), a PR can be raised to use the class from cv_bridge instead.

Done: https://github.com/ros2/demos/issues/583

**Comment by ZhenshengLee** [comment]
Any plan to merge this pr to `humble` branch?

**Comment by ijnek** [comment]
@ZhenshengLee feature additions won't be backported to already released distributions, only bug fixes will be backported.

**Pull request merged**
