### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by sloretz** [comment]
Fixes https://github.com/ros-perception/vision_opencv/pull/330#discussion_r431004671

**Comment by MatthijsBurgh** [comment]
Right now travis keep failing because of catkin. It requires a new release, see https://github.com/catkin/catkin_tools/issues/603.

**Comment by sloretz** [comment]
@mjcarroll is it ok to ignore travis failures in this repo? It looks like the ROS buildfarm PR jobs pass.

**Comment by mjcarroll** [comment]
Yes, we can ignore for now and revisit once catkin/catkin_tools#603 lands.

**Comment by mjcarroll** [comment]
And actually, since that is the case, @MatthijsBurgh can we separate this into just fixing the typo, and open a second PR with the travis changes?

**Comment by MatthijsBurgh** [comment]
I dropped the travis changes. So this PR only contains the typo fix.

**Review by sloretz — APPROVED** [review]

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
