### PR TITLE
Convert RGB image to BGR to display

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by vrabaud** [comment]
Actually, I found a bug: what if you don't specify the encoding but ask for dynamic scaling ? I think you should simply remove this 5-line if section no ?
Also, please update the doc to say that it is converting to BGR8 by default, thx.

**Comment by wkentaro** [comment]
> I think you should simply remove this 5-line if section no ?

What line do you specify?

**Comment by vrabaud** [comment]
Just remove that block: https://github.com/ros-perception/vision_opencv/blob/2be3371fa6f793b9562f0f891fe561effd511ca9/cv_bridge/src/cv_bridge.cpp#L305

**Comment by wkentaro** [comment]
Why?

```
$ find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
find: `/home/travis/.ros/test_results': No such file or directory
$ for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done
=== /home/travis/.ros/log/rostest-* ===
cat: /home/travis/.ros/log/rostest-*: No such file or directory

Done. Your build exited with 1.
```

**Comment by vrabaud** [comment]
Well, you broke a test: 

```
[ RUN      ] CvBridgeTest.endianness    
unknown file: Failure                   
C++ exception with description "Unknown encoding " thrown in the test body. 
[  FAILED  ] CvBridgeTest.endianness (0 ms) 
```

Why did you modify that piece of code ? It's independent from the initial problem no ?

**Comment by wkentaro** [comment]
You mean this change is not needed?

https://github.com/wkentaro/vision_opencv/commit/202e5c8d35435740477c15d29a7fd1e17d3db5ab?w=1

**Comment by vrabaud** [comment]
aaaaaaaaaaaah, totally sorry, I understand the confusion, I went too fast .... I meant:
https://github.com/ros-perception/vision_opencv/blob/2be3371fa6f793b9562f0f891fe561effd511ca9/cv_bridge/src/cv_bridge.cpp#L536

**Comment by wkentaro** [comment]
I see, I updated the commit.

**Comment by vrabaud** [comment]
Well, you should remove the lines you added in https://github.com/wkentaro/vision_opencv/commit/93b6c531fa46ae6dbacee966a0f17d4d126ad2d1
The lines below will choose BGR8 anyway.
We want BGR8 no matter what right ? Even if input is YUV422.

**Pull request merged**
