### PR TITLE
OpenCV4 Support. Take 57 

### PR DESCRIPTION
**Pull request by OAkyildiz**
As requested in #308 and #288. The original commit belongs to @solosito, I cherry-picked it into the  [melodic](https://github.com/ros-perception/vision_opencv/tree/melodic) branch. CI test is with Melodic on Bionic Beaver (as opposed to trusty).

>! Original PR's were  a) tested on kinetic w/ Thar, b) pulled from ros2

### CODE REVIEW

**Review by BarathwajAnandan — APPROVED** [review]
.

**Comment by OAkyildiz** [comment]
Should I close this?

**Comment by ghost** [comment]
Sorry, any update on this?

**Comment by OAkyildiz** [comment]
@guglielmodev I don't believe this is not an issue anymore

**Comment by mjcarroll** [comment]
OpenCV 4 support was added in the noetic release #323

**Pull request closed without merging**
