### PR TITLE
Adjust to arbitrary image channels like 32FC40

### PR DESCRIPTION
**Pull request by wkentaro**
I use 32FC40 image for object classification probabilities in 40
classes.

### CODE REVIEW

**Comment by vrabaud** [comment]
is that really useful ? Does the C version handle it ?

**Comment by wkentaro** [comment]
> Does the C version handle it ?

I have no idea how to handle this on C++ with OpenCV.
Currently, I've implemented on Python with Numpy.

> is that really useful ? 

Currently the usecase is only for object segmentation, but I think this is useful.
Below is the example:

(left) **(a) RawImage** (center) **(b) LabelImage** (right) **(c) ProbabilicImageForTargetObject**
image

The pipeline is

```
[Kinect] -> (a) RawImage -> [SegmentationNode] -> (b) LabelImage (32SC1)
                                              |-> ProbabilicImage (32FC40) -> [ChannelExtraction] -> (c) ProbabilicImage (32FC1)
```

**Comment by vrabaud** [comment]
I submitted a proper patch that works with C++ and has tests.

**Comment by wkentaro** [comment]
Thanks! That what I wanted to do but couldn't.

**Comment by vrabaud** [comment]
C++ is the way to go to keep compatibility with both.

**Comment by wkentaro** [comment]
Yeah, I've tried to change the [`getCvType` function](https://github.com/ros-perception/vision_opencv/commit/35df5c389cb599a15a8cc24d4e0d8d9f087aec14#diff-fb2cbb0564c5ce322e4a56960733ecf4R103), but did not reach the use of `CV_MAKETYPE` properly.
I think I got to know the correspondence between OpenCV type and Numpy dtype.

**Comment by vrabaud** [comment]
I wish OpenCV had that by default .... I also added support for "8U" type support (no need for "8UC1")

**Comment by wkentaro** [comment]
I see. Thank you.

**Pull request closed without merging**
