### PR TITLE
Add opencv_apps and opencv_tests to vision_opencv meta package

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by vrabaud** [comment]
I would be against opencv_tests : they are really tests, and are undocumented. Most functionalities are probably in opencv_apps too.
Sure for opencv_apps.

**Comment by garaemon** [comment]
So, Do I need to remove opencv_tests?

**Comment by vrabaud** [comment]
yes please, do remove it for now

Those tests actually do not make sense anymore: they could be part of opencv_apps. There are not real tests, just basic apps.

**Comment by garaemon** [comment]
updated

**Comment by garaemon** [comment]
:bow:

**Pull request merged**
