### PR TITLE
[cv_bridge] Implement cpp conversion of N channel image

### PR DESCRIPTION
**Pull request by wkentaro**
This is cpp version of https://github.com/ros-perception/vision_opencv/pull/141,
which is one for python.

### CODE REVIEW

**Comment by vrabaud** [comment]
Let's not duplicate the API: you should upgrade the API here: https://github.com/ros/common_msgs/blob/jade-devel/sensor_msgs/include/sensor_msgs/image_encodings.h#L130
The encodings listed there are just the common ones but you could add a comment saying that any format of the form "8UC_", "64FC_" are valid too and fix bitDepth and numChannels.

**Comment by wkentaro** [comment]
Sounds nice.

**Comment by vrabaud** [comment]
sounds doable to you ? Please don't use boost regex to get heavier dependencies but it should be fairly small to implement

**Comment by wkentaro** [comment]
Yeah, I will do it when I have time.

**Comment by wkentaro** [comment]
Sent https://github.com/ros/common_msgs/pull/91

**Comment by wkentaro** [comment]
The new commit depends on the PR ros/common_msgs#91.

**Comment by vrabaud** [comment]
please ping me again once common_msgs has been released with the added API. Thx.

**Comment by wkentaro** [comment]
common_msgs is released on shadow-fixed.

**Pull request closed without merging**
