### PR TITLE
Convert label to BGR image to display

### LINKED ISSUE #90: [cv_bridge] Support 32SC1 to visualize in cvtColorForDisplay
I think 32SC1 is usually used for label image, and label image should be visualize with converting it to RGB image.
like [skimage.color.label2rgb](http://scikit-image.org/docs/dev/api/skimage.color.html#label2rgb)

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #90

### CODE REVIEW

**Comment by k-okada** [comment]
LGTM

**Comment by wkentaro** [comment]
@vrabaud Could you please review this?

**Comment by vrabaud** [comment]
ok, that needs doc in the cvtForDisplay header.
Where did you get those colors from ? I hope it's not protected by a trademark or something.
Very nice to have otherwise.

**Comment by wkentaro** [comment]
Thank you for pointing out about color licenses.
The color definition is copied from scikit-image. https://github.com/scikit-image/scikit-image/blob/master/skimage/color/rgb_colors.py
The license is Modified BSD, and the color definition seems not protected though.

**Comment by vrabaud** [comment]
why not using colormap by the way ? http://docs.opencv.org/2.4/modules/contrib/doc/facerec/colormaps.html
It would simplify the code and license.

**Comment by wkentaro** [comment]
I didn't know that feature in opencv, thank you for sharing with me.

I tried that function and I think the problem of that function is the color changes gradually so different label looks same label some times.

**with rgbColors**
image

**with applyColorMap**
image

**Comment by wkentaro** [comment]
it would be like https://github.com/ros-perception/vision_opencv/pull/95

**Comment by vrabaud** [comment]
well, you have to think about the cases you want to solve:
- do I know the number of indices before hand ?
- can this number be predefined ? (like you did in your PR).
- do I want to change the map ? (which makes sense for depth or cluster indices)
  You can also compute those colors in a cube at runtime to make sure they are as far from each other as possible.

**Comment by wkentaro** [comment]
- do I know the number of indices before hand ? (-> no, but the unique pixel values in label image is the number in most cases)
- can this number be predefined ? (like you did in your PR). (-> In my PR, it can differentiate up to 146 clusters, in most case it's enough I think)
- do I want to change the map ? (which makes sense for depth or cluster indices) You can also compute those colors in a cube at runtime to make sure they are as far from each other as possible. (-> For depth image, yes, but for label image I don't need to change the map)

**Comment by vrabaud** [comment]
ok, let's merge that in. Please:
- rebase
- add a comment to say where you got the colors from and add the project in the copyright of the BSD license.
  Thx

**Comment by wkentaro** [comment]
I'm done.

**Comment by wkentaro** [comment]
Closes #95

**Pull request merged**
