### PR TITLE
update CMakeLists.txt for Windows build environment

### PR DESCRIPTION
**Pull request by kejxu**
update `CMakeLists.txt` for Windows build environment
- `RUNTIME_OUTPUT_DIRECTORY` is needed so that `.dll` would be exported
- add `if(MSVC)` special handling
- `RUNTIME DESTINATION` should be `${CATKIN_GLOBAL_BIN_DESTINATION}` for `.dll` on Windows based on catkin recommendation

### CODE REVIEW

**Comment by mjcarroll** [comment]
@kejxu or @seanyen Same here with the rebase.

**Comment by kejxu** [comment]
@mjcarroll seems like travis is working now =)

**Comment by seanyen** [comment]
@mjcarroll Just a friendly ping, this is ready for review and merge.

**Comment by seanyen** [comment]
@mjcarroll Friendly ping.

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
