### PR TITLE
add cv2_to_cmprsimgmsg

### PR DESCRIPTION
**Pull request by talregev**
add cv2_to_cmprsimgmsg
- convert from cv2 image to compressed image ros msg.

### CODE REVIEW

**Comment by talregev** [comment]
@vrabaud, I am not sure why the build is fail. I check the python code, and it work correctly.

**Comment by talregev** [comment]
@vrabaud can you check and approve?

**Comment by vrabaud** [comment]
The error in Travis is explicit: you are using rospy.Time.now() which is not instantiated.
You should not use that but have it be a parameter of the functions.
Also, cmprsimgmsg_to_cv2 is a pretty bad naming: I read it as compares image message to cv2.
compressed_img_msg_to_cv2 maybe ?

**Comment by talregev** [comment]
ok. Thanks for your feedback! :+1:

**Comment by talregev** [comment]
@vrabaud please tell me what you think.

**Comment by talregev** [comment]
@vrabaud Thanks for your help.
I squash the commits, can you check and approve?

Thanks, 
Tal.

**Comment by vrabaud** [comment]
To follow on #132

**Pull request closed without merging**
