### PR TITLE
Run travis on trusty to test indigo

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
tried on my repo https://github.com/wkentaro/vision_opencv/pull/1

**Comment by vrabaud** [comment]
thx for fixing !

**Comment by vrabaud** [comment]
hmmm, your file did not work and the modifications I brought neither ... Any idea ?

**Comment by wkentaro** [comment]
you mean this line, don't you? https://travis-ci.org/wkentaro/vision_opencv/jobs/92996784#L1659

```
ImportError: "from catkin_pkg.package import parse_package" failed: No module named catkin_pkg.package 
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH. 
CMake Error at /opt/ros/indigo/share/catkin/cmake/safe_execute_process.cmake:11 (message): 
  execute_process(/opt/python/2.7.10/bin/python 
  "/opt/ros/indigo/share/catkin/cmake/parse_package_xml.py" 
  "/opt/ros/indigo/share/catkin/cmake/../package.xml" 
  "/home/travis/ros/ws_vision_opencv/build/cv_bridge/catkin/catkin_generated/version/package.cmake") 
  returned error code 1                 
Call Stack (most recent call first):    
  /opt/ros/indigo/share/catkin/cmake/catkin_package_xml.cmake:63 (safe_execute_process) 
  /opt/ros/indigo/share/catkin/cmake/all.cmake:151 (_catkin_package_xml)
  /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:20 (include) 
  CMakeLists.txt:4 (find_package)       


-- Configuring incomplete, errors occurred! 
See also "/home/travis/ros/ws_vision_opencv/build/cv_bridge/CMakeFiles/CMakeOutput.log". 
See also "/home/travis/ros/ws_vision_opencv/build/cv_bridge/CMakeFiles/CMakeError.log". 
```

I have tried to fix this, but `python-catkin-pkg` is already installed, so actually I have no idea why this happens..:(
@k-okada do you have idea? (there was no error when running on hydro? I'm asking you because you are the author of this file.)

**Comment by wkentaro** [comment]
https://github.com/ros-perception/vision_opencv/pull/87
should fix this problem. 
I tried on my repo: https://github.com/wkentaro/vision_opencv/pull/3

**Comment by k-okada** [comment]
I think you already found solution, but here is memo

http://lists.ros.org/pipermail/ros-users/2015-October/069721.html
https://github.com/jsk-ros-pkg/jsk_travis/issues/172#issuecomment-148700171

2015年11月25日水曜日、Kentaro Wadanotifications@github.comさんは書きました:

> #87 https://github.com/ros-perception/vision_opencv/pull/87
> should fix this problem.
> I tried on my repo: wkentaro#3
> https://github.com/wkentaro/vision_opencv/pull/3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-perception/vision_opencv/pull/85#issuecomment-159575126
> .

## 

## 

◉ Kei Okada

**Comment by 130s** [comment]
@wkentaro just FYI, I think you already encountered the same issue before in another repository https://github.com/jsk-ros-pkg/jsk_travis/issues/172#issuecomment-148981034

**Comment by wkentaro** [comment]
Thanks.
I totally forgot about the previous issue that was fixed too easily thanks to @k-okada.

**Pull request merged**
