### PR TITLE
attempt to remove circular dependent packages

### PR DESCRIPTION
**Pull request by k-okada**
see #120 for discussion

### CODE REVIEW

**Comment by vrabaud** [comment]
We should not jeopardize the quality of the tests. I moved opencv_apps to its own repo: opencv_apps has moved and you have write access to it: https://github.com/ros-perception/opencv_apps
@k-okada , you have write access, feel free to release whenever.

**Comment by k-okada** [comment]
thank you

**Comment by k-okada** [comment]
@vrabaud can you create https://github.com/ros-gbp/opencv_apps-release repository and add write access to me, thanks i advance!

**Comment by vrabaud** [comment]
Let's keep it in ros-perception: https://github.com/ros-perception/opencv_apps-release. You're an admin there.

**Comment by k-okada** [comment]
Thanks!, I'm afraid I have admin access there, please check if @k-okada
have permissions,  please check it again.

```
==> git push --dry-run
remote: Permission to ros-perception/opencv_apps-release.git denied to
k-okada.
fatal: unable to access '
https://github.com/ros-perception/opencv_apps-release.git/': The requested
URL returned error: 403
Cannot push to remote release repository.

```

## 

◉ Kei Okada

**Comment by k-okada** [comment]
sorry, I did not noticed `vrabaud invited you to
ros-perception/opencv_apps-release` e-mail, now it's fine.

## 

◉ Kei Okada

**Pull request closed without merging**
