### PR TITLE
update maintainer

### PR DESCRIPTION
**Pull request by ijnek**
@audrow as we discussed (and agreed on) by email, I am willing to become a maintainer of this repository.

Signed-off-by: Kenji Brameld <kenjibrameld@gmail.com>

### CODE REVIEW

**Review by audrow — COMMENTED** [review]
Would you add yourself as a reviewer here, too? https://github.com/ros-perception/vision_opencv/blob/ros2/opencv_tests/setup.py#L19-L20

Also, I don't have permission to give you write access. I believe @clalancette does (out of the office this week).

**Comment by ijnek** [comment]
@audrow Thanks for picking that up, I also found a duplicated author tag of Ethan Gao so I removed one of them.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
@ijnek FYI, I've also invited you to have write access.

**Comment by ijnek** [comment]
@clalancette thanks, I can confirm I've got access.

**Comment by ijnek** [comment]
@clalancette and @mjcarroll 

In addition to maintaining the ROS 2 branches, I'm happy to review and merge PRs against ``noetic``, but I don't have acccess to [ros-gbp/vision_opencv-release](https://github.com/ros-gbp/vision_opencv-release). Who should I tag if a release is required for changes in ``noetic``?

Honestly I prefer if someone who is a user of ROS 1 maintains the ROS 1 PRs/Issues. But if that's not going to happen, I'd rather go the extra step and review the PRs that aren't going to get reviewed otherwise.

**Comment by clalancette** [comment]
@ijnek I ended up just giving you write access to https://github.com/ros-gbp/vision_opencv-release , so you can do ROS 1 releases as well.  Hopefully that works well enough for you.

**Comment by ijnek** [comment]
Thanks @clalancette !

**Pull request merged**
